repos:
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
        stages: ['commit']

-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
        stages: ['commit']
