site_name: TensorFlow Similarity
repo_url: https://github.com/tensorflow/similarity
theme:
  name: material
  logo: assets/logo.svg
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
plugins:
- autorefs
- search
- mkdocstrings:
    custom_templates: mkdocstrings
    watch:
     - ../tensorflow_similarity/